---
title: Welcome to Tyler's Project Space
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/img
  values:
    image: true
remote_theme: mmistakes/minimal-mistakes@4.17.2
description: An extension of arbatrarium
repository: mcmasty/mcmasty.github.io
