---
title: tlm13
email: ""
description: "Likes thinking and learning, and dealing with the magic layer between goals and action plans."

url: https://tlm13.com

twitter_username: username
github_username: mcmasty
minimal_mistakes_skin: "dirt"
search: true
markdown: kramdown
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"

remote_theme: "mmistakes/minimal-mistakes@4.20.2"
permalink: "/:year/:categories/:title/"
paginate: 5
paginate_path: /blog/page:num/
breadcrumbs: true  # disabled by default
timezone: America/New_York

# Pagination Settings for v2 ...
#pagination:
#  enabled: true
#  per_page: 1
#  permalink: '/page/:num/'
#  title_suffix: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true

# Produces a cleaner folder structure when using categories
#permalink: /:year/:month/:title.html

include:
- _pages

plugins:
#- jekyll-paginate
#- jekyll-paginate-v2
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache


# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-159960294-1" # Replace this with your ID, or delete
    anonymize_ip         : true

author:
  name: Tyler McMaster
  avatar: https://cdn.filestackcontent.com/4nqKY0PSF62ZHEgNZEQ8
  bio: "Enjoys thinking, learning, and chewing on problems."
  links:
  - label: Website
    icon: fas fa-fw fa-link
    url: https://tlm13.com
#  - label: Twitter
#    icon: fab fa-fw fa-twitter-square
#    url: https://twitter.com/
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/mcmasty
#  - label: Instagram
#    icon: fab fa-fw fa-instagram
#    url: https://instagram.com/
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/mcmasty/



footer:
  links:
#  - label: Twitter
#    icon: fab fa-fw fa-twitter-square
#    url: https://twitter.com/
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/mcmasty
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/in/mcmasty/

collections:
  projects:
    output: true
    permalink: /:collection/:path

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      related: true

category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"



compress_html:
  clippings: all
  ignore:
    envs: development
